### ISSUE TITLE
[state=Graceful] SshException: Write attempt on closing session: SSH_MSG_CHANNEL_EOF

### ISSUE THREAD

**Issue by Harikrishna1307** [apache/mina-sshd#418] opened 2023-09-20 08:06 UTC
### Version

2.10.0

### Bug description

When we can close the channel and session objects after writing the commends successfully into the channel, we are getting below warning message. Could you please help me on this?

WARN ---[state=Graceful] **SshException: Write attempt on closing session: SSH_MSG_CHANNEL_EOF**
		
SshException thows  in sshd-common-2.10.0.jar & sshd-core-2.10.0.jar

ChannelSession.class
asyncIn = new ChannelAsyncOutputStream(this, SshConstants.SSH_MSG_CHANNEL_DATA) {
                @SuppressWarnings("synthetic-access")
                @Override
                protected CloseFuture doCloseGracefully() {
                    // First get the last packets out
                    CloseFuture result = super.doCloseGracefully();
                    result.addListener(f -> {
                        try {
                            // The channel writes EOF directly through the SSH session
                            sendEof();
                        } catch (IOException e) {
                            getSession().exceptionCaught(e);
                        }
                    });
                    return result;
                }
            };
			
	AbstractSsshFuture.class		
			protected void notifyListener(SshFutureListener<T> l) {
        try {
            T arg = asT();
            ThreadUtils.runAsInternal(() -> {
                l.operationComplete(arg);
                return null;
            });
        } catch (Throwable t) {
            warn("notifyListener({}) failed ({}) to invoke {}: {}",
                    this, t.getClass().getSimpleName(), l, t.getMessage(), t);
        }
    }

### Actual behavior

WARN ---[state=Graceful] SshException: Write attempt on closing session: SSH_MSG_CHANNEL_EOF

### Expected behavior

while closing the channel and session objects, below warn message should not be displayed in logs.
WARN ---[state=Graceful] **SshException: Write attempt on closing session: SSH_MSG_CHANNEL_EOF

### Relevant log output

```Shell
WARN ---[state=Graceful] SshException: Write attempt on closing session: SSH_MSG_CHANNEL_EOF
```

**Comment by tomaswolf** [comment] 2023-09-21 17:38
This sounds like a duplicate of the recently fixed #410. Does this still occur with 2.10.1-SNAPSHOT available from the [Apache Snapshot repository](https://repository.apache.org/content/repositories/snapshots)?

**Comment by tomaswolf** [comment] 2023-09-25 21:08
@Harikrishna1307 : does this still occur with 2.10.1-SNAPSHOT?

**Comment by Harikrishna1307** [comment] 2023-09-26 06:49
@tomaswolf  Good Morning! My apologies for the late reply, do you have any official release date for 2.10.1?  2.10.1-SNAPSHOT is not available in maven repository, We are not able to add the dependency in pom.xml, Could you help me what are all jars I need replace and test it?

**Comment by tomaswolf** [comment] 2023-09-26 08:21
@Harikrishna1307 : The snapshot is available in the Apache Snapshots repository. See message above. You many need to allow snapshots explicitly.

**Comment by tomaswolf** [comment] 2023-10-06 21:27
Closing as a duplicate of #410.

**Closed by tomaswolf** 2023-10-06 21:27 UTC
