### ISSUE TITLE
mina-core 2.1.9 not compatible with 2.1.8 on Java 8? 

### ISSUE THREAD

**Issue by garydgregory** [apache/mina-sshd#646] opened 2024-12-19 13:55 UTC
### Version

2.1.9

### Bug description

Building Apache Commons VFS with 2.1.9 on Java 8, we get:
```
[INFO] Running org.apache.commons.vfs2.provider.sftp.SftpProviderStreamProxyModeTestCase
Error: Exception in thread "pool-17-thread-9" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.apache.mina.core.buffer.AbstractIoBuffer.flip(AbstractIoBuffer.java:462)
	at org.apache.sshd.common.session.AbstractSession.sendIdentification(AbstractSession.java:589)
	at org.apache.sshd.server.session.ServerSession.sendServerIdentification(ServerSession.java:331)
	at org.apache.sshd.server.session.ServerSession.<init>(ServerSession.java:91)
	at org.apache.commons.vfs2.provider.sftp.SftpPutChannelTestCase$CustomServerSession.<init>(SftpPutChannelTestCase.java:42)
```
From: https://github.com/apache/commons-vfs/actions/runs/12405540490/job/34634431811
Full build log copied here: https://gist.github.com/garydgregory/a7f02f5f9e33c371175422d95645c1a0

To reproduce minimally:
```
git clone https://github.com/apache/commons-vfs.git
cd commons-vfs
git checkout 3e8a1a59ab717a8197a9713441790d3908b4c00a
mvn -pl commons-vfs2 clean test -Dtest=SftpProviderStreamProxyModeTestCase
```
Using:
```
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec
Java version: 1.8.0_432, vendor: IBM Corporation, runtime: /Library/Java/JavaVirtualMachines/ibm-semeru-open-8.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.2", arch: "x86_64", family: "mac"
```

### Actual behavior

```
[INFO] Running org.apache.commons.vfs2.provider.sftp.SftpProviderStreamProxyModeTestCase
Error: Exception in thread "pool-17-thread-9" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.apache.mina.core.buffer.AbstractIoBuffer.flip(AbstractIoBuffer.java:462)
	at org.apache.sshd.common.session.AbstractSession.sendIdentification(AbstractSession.java:589)
	at org.apache.sshd.server.session.ServerSession.sendServerIdentification(ServerSession.java:331)
	at org.apache.sshd.server.session.ServerSession.<init>(ServerSession.java:91)
	at org.apache.commons.vfs2.provider.sftp.SftpPutChannelTestCase$CustomServerSession.<init>(SftpPutChannelTestCase.java:42)
```

### Expected behavior

With Java 17, all is well:
```
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.775 s -- in org.apache.commons.vfs2.provider.sftp.SftpProviderStreamProxyModeTestCase
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.728 s
[INFO] Finished at: 2024-12-19T08:54:03-05:00
[INFO] ------------------------------------------------------------------------
```

### Relevant log output

```Shell
https://gist.github.com/garydgregory/a7f02f5f9e33c371175422d95645c1a0
```

**Comment by garydgregory** [comment] 2024-12-19 13:56
This could be due to not compiling with the Java 8 source and target flags set properly to Java 8.

**Comment by tomaswolf** [comment] 2024-12-19 15:22
From the stack trace, it looks that the problem is in mina-core 2.1.9: probably compiled with javac > 8 but without `--release` option. mina-core does not belong to Apache MINA sshd but to [Apache MINA](https://github.com/apache/mina), which uses Jira as its issue tracker.

Besides, I notice Apache Commons VFS [uses Apache MINA sshd 0.8.0](https://github.com/apache/commons-vfs/blob/cc1f40e707e181988465ded0755bd6d433c10b8e/pom.xml#L510). (Unclear whether this is in tests only. The comment says so, but the dependency does not have test scope.) This version is ages old and dates back to a time when javac didn't even have a `--release` option. We will definitely not do anything about such an old version of Apache MINA sshd.

**Comment by chrjohn** [comment] 2024-12-19 15:55
https://issues.apache.org/jira/plugins/servlet/mobile#issue/DIRMINA-1183

**Comment by garydgregory** [comment] 2024-12-19 15:59
And please accept my apologies for creating this ticket in the wrong place! 🤦

**Comment by tomaswolf** [comment] 2024-12-19 18:50
No problem. Closing a s duplicate of [DIRMINA-1183](https://issues.apache.org/jira/browse/DIRMINA-1183).

**Closed by tomaswolf** 2024-12-19 18:50 UTC
Labels: not sshd
