### ISSUE TITLE
Regression in HostConfigEntry parsing

### ISSUE THREAD

**Issue by pikinier20** [apache/mina-sshd#402] opened 2023-08-10 09:28 UTC
### Version

2.10.0

### Bug description

After updating the library version to 2.10.0 I couldn't connect to my remote host. I found out that the problem is caused by regression in parsing the ssh config. In 2.9.2 version, in `HostConfigEntry.toHostConfigEntryResolver` the lambda at the end called `normalizeEntry` which caused expansion of `~` char etc. In 2.10.0, the `normalizeEntry` is gone and `resolveIdentityFilePath` looks like it's never called.

### Actual behavior

The identity file path is not expanded to absolute path which prevents loading the identity key

### Expected behavior

Assuming it was expanded in 2.9.2 and is not mentioned in release notes, it should still expand the path.

**Comment by tomaswolf** [comment] 2023-08-10 10:18
This is a duplicate of [SSHD-1332](https://issues.apache.org/jira/browse/SSHD-1332) and was fixed for the next version in commit 226b25431.

See file [CHANGES.md](https://github.com/apache/mina-sshd/blob/master/CHANGES.md#bug-fixes).

**Closed by tomaswolf** 2023-08-10 10:18 UTC
